CREATE TABLE `products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `path` VARCHAR(120) NULL,
  `createdAt` VARCHAR(45) NULL DEFAULT 'CURRENT_TIMESTAMP',
  `updatedAt` VARCHAR(45) NULL DEFAULT 'null',
  PRIMARY KEY (`id`));